require("dotenv").config();

module.exports = {
  NODE_ENV: process.env.NODE_ENV || "development",
  MONGO_DATABASE_DEV: process.env.MONGO_DATABASE_DEV,
  AWS_ACCESS_KEY: process.env.AWS_ACCESS_KEY,
  AWS_SECRET_KEY: process.env.AWS_SECRET_KEY,
  API_VERSION: process.env.API_VERSION,

  EMAIL_FROM:process.env.EMAIL_FROM,
  SENDGRID_USERNAME:process.env.SENDGRID_USERNAME,
  SENDGRID_PASSWORD:process.env.SENDGRID_PASSWORD,


  JWT_SECRETE_KEY: process.env.JWT_SECRETE_KEY,
  JWT_EXPIRY_TIME: process.env.JWT_EXPIRY_TIME,
  REFRESH_TOKEN_SECRET: process.env.REFRESH_TOKEN_SECRET,
  REFRESH_TOKEN_EXPIRY: process.env.REFRESH_TOKEN_EXPIRY,

  CRYPTO_CANDLE_URL: process.env.CRYPTO_CANDLE_URL,
  CRYPTO_TRACKER_URL: process.env.CRYPTO_TRACKER_URL,
  FIREBASE_API_KEY: process.env.FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN: process.env.FIREBASE_AUTH_DOMAIN,
  FIREBASE_PROJECT_ID: process.env.FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET: process.env.FIREBASE_STORAGE_BUCKET,
  FIREBASE_MESSAGING_SENDER_ID: process.env.FIREBASE_MESSAGING_SENDER_ID,
  FIREBASE_APP_ID: process.env.FIREBASE_APP_ID,
  FIREBASE_MEASUREMENT_ID: process.env.FIREBASE_MEASUREMENT_ID,
  REDIS_PASSWORD: process.env.REDIS_PASSWORD,
  REDIS_HOST: process.env.REDIS_HOST,
  REDIS_PORT: process.env.REDIS_PORT,
};
